### ISSUE TITLE
Empty fields in reportassign.php

### ISSUE THREAD

**Issue by moodleulpgc** [thepurpleblob/moodle-report_assign#1]
Hi,
If you do NOT check any user fields in config report_assign | profilefields then the function 
get_profilefields() in classes/output/reportassign.php wil fail with a fatal error due to an emty value is passed to get_string.

The solution I have implemented in my local install is to change line 60 to eliminate empty values from the array;

- $fields = explode(',', get_config('report_assign', 'profilefields'));
+ $fields = array_filter(explode(',', get_config('report_assign', 'profilefields')));

**Comment by thepurpleblob** [comment]
Oops. Thanks for the report. I'll get that sorted. 

Sounds like an elegant solution too!
