### ISSUE TITLE
Add additional assignment notifications (2)

### ISSUE THREAD

**Issue by GT-Bob** [thepurpleblob/moodle-report_assign#16]
I'd like to able to add a specific user (or just an email address) who would be alerted any time a grade was released. For example our Assessments Dept. This user would not need to be enrolled onto the course necessarily. Thanks. Bob.

**Comment by thepurpleblob** [comment]
I'm not going to fix this here but I am planning on creating a new plugin to provide extra, configurable notifications for Assignment.
