### ISSUE TITLE
Table incorrectly formatted when no profile fields are selected

### ISSUE THREAD

**Issue by thepurpleblob** [thepurpleblob/moodle-report_assign#19]
A spurious '-' is added to the data output in place of profile fields when none are selected.

**Comment by tonyjbutler** [comment]
@thepurpleblob I may be wrong but were the changes made to classes/lib.php in 1f1066822e95448c3380d5277167e70a65995ddb reverted in d161d8030febe8e8366b2d07b0eec6f10e64156f?

This doesn't seem to be fixed in v1.2.7 and I'm wondering if that's the reason.

**Comment by thepurpleblob** [comment]
Not a clue. I don't remember. 

I need to check this for 3.11 and I want to do some new things too. If there are any outstanding issues I would recommend raising them as a new Issue with all the details. Makes my life a bit easier.

**Comment by tonyjbutler** [comment]
Then I refer you to https://github.com/thepurpleblob/moodle-report_assign/issues/29.
