### ISSUE TITLE
Skip activities deleted in the course

### ISSUE THREAD

**Issue by wiktorwandachowicz** [thepurpleblob/moodle-report_assign#23]
When a teacher deletes one of the assignments in the course, the report still displays removed elements.

The reason for that is inside `report_assign\lib::get_assignments()` function.
All `course_module` instances are iterated over, not taking into account their `deletioninprogress` property.

Proposed solution is to check `deletioninprogress` to skip activities deleted in the course:

        public static function get_assignments($id) {
            /* ... some code removed for brevity ... */

            $assigns = $modinfo->instances['assign'];

            // Add plagiarism and feedback status.
            $assignments = [];
            foreach ($assigns as $cm) {
                /* --- BEGIN patch --- */
                $rec = $cm->get_course_module_record();
                if ($rec->deletioninprogress) {
                    continue;
                }
                /* --- END patch --- */
                $context = \context_module::instance($cm->id);
                $assignment = new \assign($context, $cm, $course);
                $instance = $assignment->get_instance();
                $instance->urkundenabled = self::urkund_enabled($instance->id);
                $instance->turnitinenabled = self::turnitin_enabled($instance->id);
                $assignments[$instance->id] = $instance;
            }

            return $assignments;
        }

**Comment by thepurpleblob** [comment]
Any chance you could work this up as a pull request?

**Comment by wiktorwandachowicz** [comment]
Please see the pull request #28.

**Comment by thepurpleblob** [comment]
Pull request has been added. Thanks very much
