### ISSUE TITLE
Include Submissions and Feedback for Assignments with Multiple Attempts

### ISSUE THREAD

**Issue by DownesAyr** [thepurpleblob/moodle-report_assign#26]
Great plugin. However, as a potential enhancement...

In my institution multiple attempts are extremely common. They may be scale graded as requiring to resubmit for the first few attempts before their eventual passing attempt. It is desirable to have multiple submissions and the feedback at each stage accessible. To illustrate this see image below:
![image](https://user-images.githubusercontent.com/22812156/113275239-79db3d80-92d6-11eb-809b-a315cdf7581a.png)

It would be really great if this could be incorporated into your plugin, so they can be bulk downloaded. It works excellently except it only ever gives the current submission and feedback in the bulk download.

**Comment by thepurpleblob** [comment]
Are we talking about "reopened attempts"?  We've never used that at all, so I don't really know what it does.

**Comment by DownesAyr** [comment]
Yes it is the reopened attempts feature. 

We have scale grades of **pass** or **resubmit**. The maximum grade is accordingly set to **2**. 
![image](https://user-images.githubusercontent.com/22812156/115246284-a805ad80-a11d-11eb-8e89-754655e1cee2.png)

If a student is graded with **resubmit** the attempt is reopened (appearing blank initially as it awaits their next attempt). 

However the 'view a different attempt' button as shown in my screenshot lets a teacher choose an older attempt which loads in the normal way showing the submission file, annotate PDF, feedback files, and text feedback etc given on that particular attempt. It is basically a way of keeping an evidence trail of multiple attempts but only requiring a single assignment activity.

Hope this helps clarify how we use it and how it works.

**Comment by thepurpleblob** [comment]
To be honest, the reopen feature is not something that I have ever encountered before or really know how it works. Nobody I deal with uses it. 

I'll leave this sitting but I don't have much motivation to support it. Sorry.

**Comment by DownesAyr** [comment]
That's okay I understand. Didn't think it would be a quick or easy enhancement. I always thought it was more a process that has greater suitability for further education / college sector than higher education / uni sector.

Thought it worth a mention anyway.

Thanks.

**Comment by thepurpleblob** [comment]
I'm going to close this as "will not fix". I have no use for this feature so can't justify spending time on it. If you want to send a pull request I'd be more than happy to incorporate it.
