### ISSUE TITLE
Table incorrectly formatted when no profile fields are selected

### ISSUE THREAD

**Issue by tonyjbutler** [thepurpleblob/moodle-report_assign#29]
Initially posted as a comment in the original issue (https://github.com/thepurpleblob/moodle-report_assign/issues/19) but I guess I can't expect it to get much attention in an issue that was closed more than a year ago:

> @thepurpleblob I may be wrong but were the changes made to classes/lib.php in 1f10668 reverted in d161d80? (Edit: and a few other files too?)
> 
> This doesn't seem to be fixed in v1.2.7 and I'm wondering if that's the reason.

**Comment by thepurpleblob** [comment]
Can you enlarge a bit. As I commented in the other Issue, I don't really remember the problem. Do you have an example/screenshot?

**Comment by thepurpleblob** [comment]
...but it looks like you may be right. Strange...

**Comment by tonyjbutler** [comment]
I haven't actually experienced the issue myself (but I've asked my colleague who discovered it to comment). I'd only observed the apparent revert of the fix commit when I was trying to figure out why it was apparently still broken after being fixed.

**Comment by thepurpleblob** [comment]
Ok - I'm struggling to remember exactly what the problem was. Even though I found it myself :-D. 

I need to have a proper look.

**Comment by TimEllis** [comment]
![Screenshot 2021-05-21 124606](https://user-images.githubusercontent.com/3763555/119132403-8ce6d000-ba32-11eb-9169-2bb109f4dbcb.jpg)
The issue occurs if you have no profile fields selected in the plugin settings in site admin. The first row is fine but all subsequent rows have a spurious column entry which pushed them all to the right

**Comment by thepurpleblob** [comment]
Ok - got it. I remember now. 

It does indeed sound like a regression. I'll get this sorted as soon as possible.

**Comment by tonyjbutler** [comment]
Thanks Howard.
